### PR TITLE
Added V2 version of Campaigns

### PR DESCRIPTION
**Pull request by JohnnyWalkerDesign**
Retrieve and RetrieveV2 have now been tested.

### CODE REVIEW

**Comment by pawelsawicz** [comment]
Let's wait with this PR because I am about to finish complete push that will contain all campaigns endpoints

**Comment by pawelsawicz** [comment]
Closed as it was fixed already. But thanks for PR! :+1:

**Comment by JohnnyWalkerDesign** [comment]
Oops. Don't know how I missed that!

**Comment by JohnnyWalkerDesign** [comment]
Ah, I see. Good stuff.

**Pull request closed without merging**
