### PR TITLE
Converting the tests to php_unit

### PR DESCRIPTION
**Pull request by timmarsh**
Ive converted the tests (for the most part - couldnt get one of the charity ones to work) , to use php_unit. 
Ive also started adding in some other tests (and will continue too).

I think this makes the api more open, and more easily understandable. It feel it also makes it a good base for example implementations too. 
at the moment there are 41 tests, 57 assertions

### CODE REVIEW

**Comment by pawelsawicz** [comment]
Hey, tomorrow I will start doing code review thanks for this big chunk of updates

**Comment by timmarsh** [comment]
@pawelsawicz  - cool, thankyou - dont hesitate to get in tough if you've got any questions/comments on it

**Comment by pawelsawicz** [comment]
I checked and it seems very good. I really like that you have used composer for packages. Going to merge it today.

**Comment by timmarsh** [comment]
thats great - thankyou.

**Pull request merged**
